### ISSUE TITLE
Make MantiGo pip-installable

### ISSUE THREAD

**Issue by krother** [JoNiederhut/manti_go#4]
- this ticket requires the folder structure #3 to be done first
- follow the guide on [https://www.academis.eu/posts/software_engineering/pip_setup.md](https://www.academis.eu/posts/software_engineering/pip_setup.md) to create the `setup.py` file
- the commands that should work are `pip install --editable dot` and `pip install <github_address>` but not `pip install mantigo`

**Comment by ValentinRupp-Pardos** [comment]
solved #4
